import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="emerald" lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className='p-5 my-5 mx-10'>
          {children}
        </div>
        <footer className=" fixed bottom-0 left-0 right-0 h-12 flex justify-center items-center bg-gray-200">
      © Copyright {new Date().getFullYear()} Bored App | Made by{' '}
        <a href="https://github.com/KeturahDev"><span className="mx-1">Keturah Howard</span></a>
    </footer>
      </body>
    </html>
  )
}
