import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme="emerald" lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className='p-5 my-5'>
          {children}
        </div>
      </body>
    </html>
  )
}
